#!/bin/bash
sudo apt remove ros-kinetic-robotnik-sensors -y
sudo apt remove ros-kinetic-robotnik-msgs -y
sudo apt remove ros-kinetic-rcomponent -y
sudo apt remove ros-kinetic-imu-manager -y
sudo apt remove ros-kinetic-robot-localization-utils -y
sudo apt remove ros-kinetic-robotnik-modbus-io -y
sudo apt remove ros-kinetic-robotnik-base-hw -y
sudo apt remove ros-kinetic-marker-mapping -y
sudo apt remove ros-kinetic-summit-xl-common -y
sudo apt remove ros-kinetic-summit-xl-control -y
sudo apt remove ros-kinetic-summit-xl-description -y
sudo apt remove ros-kinetic-summit-xl-localization -y
sudo apt remove ros-kinetic-summit-xl-navigation -y
sudo apt remove ros-kinetic-summit-xl-perception -y
sudo apt remove ros-kinetic-summit-xl-pad -y
sudo apt remove ros-kinetic-summit-xl-robot-local-control -y
sudo apt remove ros-kinetic-poi-manager -y
sudo apt remove ros-kinetic-system-monitor -y
sudo apt remove ros-kinetic-sick-s300-laser -y
sudo apt remove ros-kinetic-rbkairos-gazebo -y
sudo apt remove ros-kinetic-rbkairos-sim -y
sudo apt remove ros-kinetic-rbkairos-sim-bringup -y
sudo apt remove ros-kinetic-rbkairos-common -y
sudo apt remove ros-kinetic-rbkairos-control -y
sudo apt remove ros-kinetic-rbkairos-description -y
sudo apt remove ros-kinetic-rbkairos-sim-bringup -y
sudo apt remove ros-kinetic-teb-local-planner -y
sudo apt remove ros-kinetic-mjpeg-server -y
sudo apt remove ros-kinetic-gazebo-ros-pkgs -y
sudo apt remove ros-kinetic-roboticsgroup-gazebo-plugins -y
sudo apt remove ros-kinetic-gazebo-msgs -y
sudo apt remove ros-kinetic-gazebo-dev -y
sudo apt remove ros-kinetic-gazebo-ros -y
sudo apt remove ros-kinetic-gazebo-ros-control -y
sudo apt remove ros-kinetic-gazebo-ros-pkgs -y
sudo apt remove ros-kinetic-gazebo-plugins -y

